package main

// tplHeader is the common header for the generated file
var tplHeader = `package {{.Package}}

// Code generated by shiftgen at {{.GenSource}}. DO NOT EDIT.

import (
	"context"
	"database/sql"
	{{$needsStrconv := false}}{{range .Inserters}}{{if and (not .HasID) (eq .IDType "string")}}{{$needsStrconv = true}}{{end}}{{end}}{{range .Updaters}}{{if eq .IDType "string"}}{{$needsStrconv = true}}{{end}}{{end}}{{if $needsStrconv}}"strconv"
	{{end}}"strings"
	"time"
	"github.com/luno/jettison/errors"
	"github.com/luno/jettison/j"
	"github.com/nileag/shift"
)
`

// tplMySQL is the MySQL template that generates InsertMySQL and UpdateMySQL methods
var tplMySQL = `
{{ range .Inserters }}
// InsertMySQL inserts a new {{.Table}} table entity using MySQL syntax. All the fields of the
// {{.Type}} receiver are set, as well as status, created_at and updated_at.
// The newly created entity id is returned on success or an error.
func (一 {{.Type}}) InsertMySQL(
	ctx context.Context, tx *sql.Tx, st shift.Status,
) ({{.IDType}}, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	{{if .CustomCreatedAt -}}
	if 一.CreatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("created_at is required")
	}
	{{end -}}
	{{if .CustomUpdatedAt -}}
	if 一.UpdatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("updated_at is required")
	}

	{{end -}}

	q.WriteString("insert into {{.Table}} set {{if .HasID}}` + "`" + `id` + "`" + `=?, {{end}}` + "`" + `{{.StatusField}}` + "`" + `=?{{if not .CustomCreatedAt}}, ` + "`" + `created_at` + "`" + `=?{{end}}{{if not .CustomUpdatedAt}}, ` + "`" + `updated_at` + "`" + `=?{{end}} ")
	args = append(args, {{if .HasID}}一.ID, {{end}}st.ShiftStatus(){{if not .CustomCreatedAt}}, time.Now(){{end}}{{if not .CustomUpdatedAt}}, time.Now(){{end}})
{{range .Fields}}
	q.WriteString(", ` + "`" + `{{.Col}}` + "`" + `=?")
	args = append(args, 一.{{.Name}})
{{end}}
	{{if .HasID}}_{{else}}res{{end}}, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
{{if not .HasID}}
	id, err := res.LastInsertId()
	if err != nil {
		return {{.IDZeroValue}}, err
	}
{{end}}
	return {{if .HasID}}一.ID{{else if eq .IDType "int64"}}id{{else}}strconv.FormatInt(id, 10){{end}}, nil
}
{{end}}{{ range .Updaters }}
// UpdateMySQL updates the status of a {{.Table}} table entity using MySQL syntax. All the fields of the
// {{.Type}} receiver are updated, as well as status and updated_at.
// The entity id is returned on success or an error.
func (一 {{.Type}}) UpdateMySQL(
	ctx context.Context, tx *sql.Tx, from shift.Status, to shift.Status,
) ({{.IDType}}, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	{{if .CustomUpdatedAt -}}
	if 一.UpdatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("updated_at is required")
	}

	{{end -}}

	q.WriteString("update {{.Table}} set ` + "`" + `{{.StatusField}}` + "`" + `=?{{if not .CustomUpdatedAt}}, ` + "`" + `updated_at` + "`" + `=?{{end}} ")
	args = append(args, to.ShiftStatus(){{if not .CustomUpdatedAt}}, time.Now(){{end}})
{{range .Fields}}
	q.WriteString(", ` + "`" + `{{.Col}}` + "`" + `=?")
	args = append(args, 一.{{.Name}})
{{end}}
	q.WriteString(" where ` + "`" + `id` + "`" + `=? and ` + "`" + `{{.StatusField}}` + "`" + `=?")
	args = append(args, 一.ID, from.ShiftStatus())

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	if n != 1 {
		return {{.IDZeroValue}}, errors.Wrap(shift.ErrRowCount, "{{.Type}}", j.KV("count", n))
	}

	return 一.ID, nil
}{{ end }}
`

// tplPostgres is the PostgreSQL template that generates InsertPostgres and UpdatePostgres methods
var tplPostgres = `
{{ range .Inserters }}
// InsertPostgres inserts a new {{.Table}} table entity using PostgreSQL syntax. All the fields of the
// {{.Type}} receiver are set, as well as status, created_at and updated_at.
// The newly created entity id is returned on success or an error.
func (一 {{.Type}}) InsertPostgres(
	ctx context.Context, tx *sql.Tx, st shift.Status,
) ({{.IDType}}, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	{{if .CustomCreatedAt -}}
	if 一.CreatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("created_at is required")
	}
	{{end -}}
	{{if .CustomUpdatedAt -}}
	if 一.UpdatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("updated_at is required")
	}

	{{end -}}

	q.WriteString("INSERT INTO {{.Table}} ({{if .HasID}}id, {{end}}{{.StatusField}}{{if not .CustomCreatedAt}}, created_at{{end}}{{if not .CustomUpdatedAt}}, updated_at{{end}}{{range .Fields}}, {{.Col}}{{end}}) VALUES (")
{{if .HasID}}
	q.WriteString("$1, $2")
	args = append(args, 一.ID, st.ShiftStatus())
	{{- if not .CustomCreatedAt}}
	q.WriteString(", $3")
	args = append(args, time.Now())
	{{- if not .CustomUpdatedAt}}
	q.WriteString(", $4")
	args = append(args, time.Now())
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 5 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- else}}
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 4 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- end}}
	{{- else}}
	{{- if not .CustomUpdatedAt}}
	q.WriteString(", $3")
	args = append(args, time.Now())
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 4 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- else}}
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- end}}
	{{- end}}
{{else}}
	q.WriteString("$1")
	args = append(args, st.ShiftStatus())
	{{- if not .CustomCreatedAt}}
	q.WriteString(", $2")
	args = append(args, time.Now())
	{{- if not .CustomUpdatedAt}}
	q.WriteString(", $3")
	args = append(args, time.Now())
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 4 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- else}}
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- end}}
	{{- else}}
	{{- if not .CustomUpdatedAt}}
	q.WriteString(", $2")
	args = append(args, time.Now())
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- else}}
	{{- range $idx, $field := .Fields}}
	q.WriteString(", ${{add 2 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{- end}}
	{{- end}}
	{{- end}}
{{end}}
	q.WriteString(")")
{{if not .HasID}}
	q.WriteString(" RETURNING id")
{{end}}
{{if .HasID}}
	_, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	return 一.ID, nil
{{else}}
	var id int64
	err := tx.QueryRowContext(ctx, q.String(), args...).Scan(&id)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	{{if eq .IDType "int64"}}return id, nil{{else}}return strconv.FormatInt(id, 10), nil{{end}}
{{end}}}
{{end}}{{ range .Updaters }}
// UpdatePostgres updates the status of a {{.Table}} table entity using PostgreSQL syntax. All the fields of the
// {{.Type}} receiver are updated, as well as status and updated_at.
// The entity id is returned on success or an error.
func (一 {{.Type}}) UpdatePostgres(
	ctx context.Context, tx *sql.Tx, from shift.Status, to shift.Status,
) ({{.IDType}}, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	{{if .CustomUpdatedAt -}}
	if 一.UpdatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("updated_at is required")
	}

	{{end -}}

	q.WriteString("UPDATE {{.Table}} SET {{.StatusField}}=$1")
	args = append(args, to.ShiftStatus())
{{- if not .CustomUpdatedAt}}
	q.WriteString(", updated_at=$2")
	args = append(args, time.Now())
{{- range $idx, $field := .Fields}}
	q.WriteString(", {{$field.Col}}=${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
{{- end}}
	{{$whereBase := add 3 (len .Fields)}}q.WriteString(" WHERE id=${{$whereBase}} AND {{.StatusField}}=${{add $whereBase 1}}")
{{- else}}
{{- range $idx, $field := .Fields}}
	q.WriteString(", {{$field.Col}}=${{add 2 $idx}}")
	args = append(args, 一.{{$field.Name}})
{{- end}}
	{{$whereBase := add 2 (len .Fields)}}q.WriteString(" WHERE id=${{$whereBase}} AND {{.StatusField}}=${{add $whereBase 1}}")
{{- end}}
	args = append(args, 一.ID, from.ShiftStatus())

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	if n != 1 {
		return {{.IDZeroValue}}, errors.Wrap(shift.ErrRowCount, "{{.Type}}", j.KV("count", n))
	}

	return 一.ID, nil
}{{ end }}
`

var mermaidTemplate = `%% Code generated by shiftgen at {{.GenSource}}. DO NOT EDIT.

stateDiagram-v2
	direction {{.Direction}}
	{{range $key, $value := .StartingPoints }}
	[*]-->{{$value}}
	{{- end }}
	{{range $key, $value := .Transitions }}
	{{$value.From}}-->{{$value.To}}
	{{- end }}
	{{range $key, $value := .TerminalPoints }}
	{{$value}}-->[*]
	{{- end }}
`
