package main

var tpl = `package {{.Package}}

// Code generated by shiftgen at {{.GenSource}}. DO NOT EDIT.

import (
	"context"
	"database/sql"
	{{$needsStrconv := false}}{{range .Inserters}}{{if and (not .HasID) (eq .IDType "string")}}{{$needsStrconv = true}}{{end}}{{end}}{{range .Updaters}}{{if eq .IDType "string"}}{{$needsStrconv = true}}{{end}}{{end}}{{if $needsStrconv}}"strconv"
	{{end}}"strings"
	"time"
	"github.com/luno/jettison/errors"
	"github.com/luno/jettison/j"
	"github.com/nileag/shift"
)

{{ range .Inserters }}

// Insert inserts a new {{.Table}} table entity. All the fields of the 
// {{.Type}} receiver are set, as well as status, created_at and updated_at. 
// The newly created entity id is returned on success or an error.
func (一 {{.Type}}) Insert(
	ctx context.Context, tx *sql.Tx, st shift.Status,
) ({{.IDType}}, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	{{if .CustomCreatedAt -}}
	if 一.CreatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("created_at is required")
	}
	{{end -}}
	{{if .CustomUpdatedAt}}
	if 一.UpdatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("updated_at is required")
	}

	{{end -}}

	// PostgreSQL uses INSERT ... VALUES syntax
	q.WriteString("INSERT INTO {{.Table}} (")
	{{if .HasID}}q.WriteString("id, "){{else}}
	
	{{end}}
	q.WriteString({{col .StatusField}})
	{{if and .CustomCreatedAt .CustomUpdatedAt (gt (len .Fields) 0)}}
	
	{{end}}
	{{if not .CustomCreatedAt}}q.WriteString(", created_at"){{end}}
	{{if not .CustomUpdatedAt}}q.WriteString(", updated_at"){{end}}
	{{if or (not .CustomCreatedAt) (not .CustomUpdatedAt)}}{{if gt (len .Fields) 0}}
	
	{{end}}{{end}}
	{{range .Fields}}
	q.WriteString(", ")
	q.WriteString({{col .Col}}){{end}}
	q.WriteString(") VALUES (")
	{{if .HasID}}
	q.WriteString("$1, $2")
	args = append(args, 一.ID, st.ShiftStatus())
	{{if not .CustomCreatedAt}}q.WriteString(", $3")
	args = append(args, time.Now())
	{{if not .CustomUpdatedAt}}q.WriteString(", $4")
	args = append(args, time.Now())
	{{range $idx, $field := .Fields}}q.WriteString(", ${{add 5 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{else}}{{range $idx, $field := .Fields}}q.WriteString(", ${{add 4 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{end}}{{else}}q.WriteString(", $3")
	args = append(args, time.Now())
	{{if not .CustomUpdatedAt}}q.WriteString(", $4")
	args = append(args, time.Now())
	{{range $idx, $field := .Fields}}q.WriteString(", ${{add 5 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{else}}{{range $idx, $field := .Fields}}q.WriteString(", ${{add 4 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{end}}{{end}}
	q.WriteString(")")
	{{if not .HasID}}q.WriteString(" RETURNING id")
	{{end}}
	{{else}}
	q.WriteString("$1")
	args = append(args, st.ShiftStatus())
	{{if not .CustomCreatedAt}}q.WriteString(", $2")
	args = append(args, time.Now())
	{{if not .CustomUpdatedAt}}q.WriteString(", $3")
	args = append(args, time.Now())
	{{range $idx, $field := .Fields}}q.WriteString(", ${{add 4 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{else}}{{range $idx, $field := .Fields}}q.WriteString(", ${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{end}}{{else}}{{if not .CustomUpdatedAt}}q.WriteString(", $2")
	args = append(args, time.Now())
	{{range $idx, $field := .Fields}}q.WriteString(", ${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{else}}{{range $idx, $field := .Fields}}q.WriteString(", ${{add 2 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}{{end}}{{end}}
	q.WriteString(")")
	q.WriteString(" RETURNING id")
	{{end}}

	{{if .HasID}}_, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	return 一.ID, nil
	{{else}}var id int64
	err := tx.QueryRowContext(ctx, q.String(), args...).Scan(&id)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	{{if eq .IDType "int64"}}return id, nil
	{{else}}return strconv.FormatInt(id, 10), nil
	{{end}}{{end}}
}
{{end}}{{ range .Updaters }}
// Update updates the status of a {{.Table}} table entity. All the fields of the
// {{.Type}} receiver are updated, as well as status and updated_at. 
// The entity id is returned on success or an error.
func (一 {{.Type}}) Update(
	ctx context.Context, tx *sql.Tx, from shift.Status, to shift.Status,
) ({{.IDType}}, error) {
	var (
		q    strings.Builder
		args []interface{}
	)

	{{if .CustomUpdatedAt -}}
	if 一.UpdatedAt.IsZero() {
		return {{.IDZeroValue}}, errors.New("updated_at is required")
	}

	{{end -}}

	// PostgreSQL uses $ placeholders
	q.WriteString("UPDATE {{.Table}} SET {{col .StatusField}}=$1")
	args = append(args, to.ShiftStatus())
	{{- if not .CustomUpdatedAt}}
	q.WriteString(", updated_at=$2")
	args = append(args, time.Now())
	{{range $idx, $field := .Fields}}q.WriteString(", {{col $field.Col}}=${{add 3 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}
	{{$whereBase := add 3 (len .Fields)}}q.WriteString(" WHERE {{col "id"}}=${{$whereBase}} AND {{col .StatusField}}=${{add $whereBase 1}}")
	{{- else}}
	{{range $idx, $field := .Fields}}q.WriteString(", {{col $field.Col}}=${{add 2 $idx}}")
	args = append(args, 一.{{$field.Name}})
	{{end}}
	{{$whereBase := add 2 (len .Fields)}}q.WriteString(" WHERE {{col "id"}}=${{$whereBase}} AND {{col .StatusField}}=${{add $whereBase 1}}")
	{{- end}}
	
	args = append(args, 一.ID, from.ShiftStatus())

	res, err := tx.ExecContext(ctx, q.String(), args...)
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return {{.IDZeroValue}}, err
	}
	if n != 1 {
		return {{.IDZeroValue}}, errors.Wrap(shift.ErrRowCount, "{{.Type}}", j.KV("count", n))
	}

	return 一.ID, nil
}{{ end }}
`

var mermaidTemplate = `%% Code generated by shiftgen at {{.GenSource}}. DO NOT EDIT.

stateDiagram-v2
	direction {{.Direction}}
	{{range $key, $value := .StartingPoints }}
	[*]-->{{$value}}
	{{- end }}
	{{range $key, $value := .Transitions }}
	{{$value.From}}-->{{$value.To}}
	{{- end }}
	{{range $key, $value := .TerminalPoints }}
	{{$value}}-->[*]
	{{- end }}
`
